# Generated by Django 5.2 on 2025-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nacionalidad', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
